### PR TITLE
Comments in clean code with examples

### PR DESCRIPTION
**Pull request by Pragatheesh**

### CODE REVIEW

**Comment by gayansanjeewa** [comment]
Can you add the following as the main point we try to convey

"Comments are often lies waiting to happen.
Code should speak for it self. Code should be the single source of truth!"

**Comment by Pragatheesh** [comment]
@gayansanjeewa I have put some notes in both the files, do you want me to abstract them to a separate file, and also to include your suggestion?

**Comment by gayansanjeewa** [comment]
Now that you mention it I think the genaral idea section of both can be extracted into one section have it as the first page, and you can incorporate what I mentioned in that. What do you think

**Comment by Pragatheesh** [comment]
Yeah will do that, so you could have a final look ;)

**Comment by Pragatheesh** [comment]
@gayansanjeewa can you have a re-look at this one

**Pull request merged**
